### PR TITLE
Implement coverage checks.

### PR DESCRIPTION
**Pull request by tanderegg**

### CODE REVIEW

**Comment by tanderegg** [comment]
@frank0631 Can you take a look?  Pretty straightforward, and I've validated that it works, but any feedback would be appreciated, thanks!

**Comment by frank0631** [comment]
😢   ::wipes away tear:: It's beautiful.

I see that it's including the file "healthcheck/templateHealthcheck.go" but that file only has constant strings in there. Could you try and skip that file by adding a codecov.yml and an "ignore" section

https://github.com/codecov/support/wiki/codecov.yml

**Comment by tanderegg** [comment]
Thanks @frank0631 :)  Actually, codecov is smart enough to ignore the constant strings, however there are a few short helper functions in that file as well, those are the ones it is checking, see here: https://codecov.io/gh/cfpb/rhobot/src/1b0a49b63e65e2ad018a99cce73618fe81864ae4/healthcheck/templateHealthcheck.go

**Comment by frank0631** [comment]
Ah. I'll be sure to write test for those helpers eventually. 
codecov looks great.

**Pull request merged**
